(require 'core (concat user-emacs-directory "core/core"))

(use-package module-rgrep)
(use-package module-org)
(use-package module-shell)
(use-package module-cl)
(use-package module-elisp)
(use-package module-markdown)
(use-package module-yaml)
(use-package module-powershell)
(use-package module-cc)
(use-package module-python)
(use-package module-scheme)
(use-package module-clojure)
